// Pinned ed25519 public keys for server-pushed signed data (ADR 0001).
//
// Production agent builds ship with one or more base64-encoded raw
// ed25519 public keys compiled in via the pinnedMapPubKeys slice
// below.  Rotation: release an agent build that pins both the
// outgoing and incoming keys, roll that out, then switch the server
// signing key, then eventually release another build that drops the
// retired key.
//
// For development, the SENTARI_TRUSTED_MAP_PUBKEYS environment
// variable can add extra keys at startup — intended for the ephemeral
// key auto-generated by a debug-mode server.  The variable is parsed
// as a comma-separated list of "key_id:base64pubkey" entries.

package scanner

import (
	"crypto/ed25519"
	"encoding/base64"
	"os"
	"strings"
)

// pinnedMapPubKeys are the keys compiled into the agent binary.  The
// production release workflow regenerates this slice from the server's
// deployed signing-key material and injects it at build time.  For
// v0.12 the slice is empty and all trust is sourced from the dev env
// override below — see ADR 0001 §§ Consequences and Implementation.
var pinnedMapPubKeys = []pinnedKey{
	// {KeyID: "primary", B64: "…32-byte raw pubkey, base64-encoded…"},
}

type pinnedKey struct {
	KeyID string
	B64   string
}

func init() {
	for _, pk := range pinnedMapPubKeys {
		if raw, err := base64.StdEncoding.DecodeString(pk.B64); err == nil {
			RegisterTrustedMapKey(pk.KeyID, ed25519.PublicKey(raw))
		}
	}

	// Dev/CI override.  Logged-visible to operators if set.
	if env := os.Getenv("SENTARI_TRUSTED_MAP_PUBKEYS"); env != "" {
		for _, entry := range strings.Split(env, ",") {
			entry = strings.TrimSpace(entry)
			id, b64, ok := strings.Cut(entry, ":")
			if !ok {
				continue
			}
			raw, err := base64.StdEncoding.DecodeString(strings.TrimSpace(b64))
			if err != nil {
				continue
			}
			RegisterTrustedMapKey(strings.TrimSpace(id), ed25519.PublicKey(raw))
		}
	}
}
