package jvm

import (
	"os"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// parsePomProperties — the line-level parser
// ---------------------------------------------------------------------------

func TestParsePomProperties_Happy(t *testing.T) {
	// Canonical shape written by maven-jar-plugin.  Comment lines start
	// with "#" and must be skipped; trailing whitespace around values
	// is preserved-then-trimmed by the parser (Maven's own writer
	// trims, but we've seen field values with trailing CRLF in the
	// wild when authors hand-edit).
	content := []byte(`#Generated by Maven
#Fri Apr 11 14:30:00 CEST 2025
version=1.4.2
groupId=org.example
artifactId=widget-core
`)
	got, err := parsePomProperties(content)
	if err != nil {
		t.Fatalf("parsePomProperties: %v", err)
	}
	if got.GroupID != "org.example" {
		t.Errorf("groupId: got %q want org.example", got.GroupID)
	}
	if got.ArtifactID != "widget-core" {
		t.Errorf("artifactId: got %q want widget-core", got.ArtifactID)
	}
	if got.Version != "1.4.2" {
		t.Errorf("version: got %q want 1.4.2", got.Version)
	}
}

func TestParsePomProperties_MissingRequiredField(t *testing.T) {
	// A pom.properties without groupId is unusable as an identity source;
	// the caller should fall through to the next extraction strategy.
	// Parser returns the partial object + no error; the caller decides
	// whether a partial pom.properties is acceptable.
	content := []byte("artifactId=x\nversion=1\n")
	got, err := parsePomProperties(content)
	if err != nil {
		t.Fatalf("parser should not fail on incomplete input: %v", err)
	}
	if got.GroupID != "" {
		t.Errorf("expected empty groupId on input without it, got %q", got.GroupID)
	}
	if got.ArtifactID != "x" || got.Version != "1" {
		t.Errorf("partial parse unexpected: %+v", got)
	}
}

func TestParsePomProperties_MalformedLines(t *testing.T) {
	// Lines without an '=' are skipped, not an error — treat them as
	// noise (accidental blank-line re-save by an editor, etc.).  Lines
	// that split correctly keep their values verbatim, so an '=' inside
	// a version (rare, but legal in exotic classifier schemes) survives.
	content := []byte("just-a-line-with-no-equals\ngroupId=a\nartifactId=b\nversion=1.0=RC1\n")
	got, err := parsePomProperties(content)
	if err != nil {
		t.Fatalf("parser should not fail on noise lines: %v", err)
	}
	if got.Version != "1.0=RC1" {
		t.Errorf("expected '=' preserved inside value, got %q", got.Version)
	}
}

func TestParsePomProperties_ExceedsSizeCap(t *testing.T) {
	// Defence against a malicious or corrupt pom.properties >64 KiB —
	// the parser must refuse rather than hang.  Use one line so we're
	// sure it's the byte count, not a line count, that triggers.
	big := []byte("version=" + strings.Repeat("x", maxPomPropertiesBytes+1))
	_, err := parsePomProperties(big)
	if err == nil {
		t.Fatalf("expected error on oversized input, got nil")
	}
}

// ---------------------------------------------------------------------------
// parseManifest — MANIFEST.MF continuation lines + OSGi headers
// ---------------------------------------------------------------------------

func TestParseManifest_OSGiHeadersWin(t *testing.T) {
	// When both OSGi Bundle-* and Implementation-* are present, OSGi
	// identity is preferred — OSGi bundles use Bundle-SymbolicName as
	// the canonical identifier and Implementation-Version tends to
	// lag or be absent.  The scanner surfaces this choice via the
	// Source field on the returned ManifestInfo.
	content := []byte("Manifest-Version: 1.0\r\n" +
		"Bundle-SymbolicName: org.eclipse.jdt.core\r\n" +
		"Bundle-Version: 3.35.0\r\n" +
		"Implementation-Title: Java Development Tools\r\n" +
		"Implementation-Version: 3.35.legacy\r\n" +
		"\r\n")
	got, err := parseManifest(content)
	if err != nil {
		t.Fatalf("parseManifest: %v", err)
	}
	if got.BundleSymbolicName != "org.eclipse.jdt.core" {
		t.Errorf("BundleSymbolicName: got %q", got.BundleSymbolicName)
	}
	if got.BundleVersion != "3.35.0" {
		t.Errorf("BundleVersion: got %q", got.BundleVersion)
	}
}

func TestParseManifest_ContinuationLines(t *testing.T) {
	// RFC 822 / JAR-spec continuation: any line starting with a single
	// space is a continuation of the previous line.  Manifest writers
	// wrap at 72 bytes routinely, so we MUST honour this or we'll
	// silently truncate long names.
	// Here the Bundle-SymbolicName spans three physical lines.
	content := []byte("Manifest-Version: 1.0\r\n" +
		"Bundle-SymbolicName: org.some.very.long.identifier.tha\r\n" +
		" t.exceeds.seventy.two.bytes.and.keeps.going.for.a.whil\r\n" +
		" e.longer.still\r\n" +
		"Bundle-Version: 1.0\r\n")
	got, err := parseManifest(content)
	if err != nil {
		t.Fatalf("parseManifest: %v", err)
	}
	want := "org.some.very.long.identifier.that.exceeds.seventy.two.bytes.and.keeps.going.for.a.while.longer.still"
	if got.BundleSymbolicName != want {
		t.Errorf("continuation join failed\n got: %q\nwant: %q", got.BundleSymbolicName, want)
	}
}

func TestParseManifest_LFOnly(t *testing.T) {
	// Some tools emit LF-only manifests (not spec-compliant, but common
	// enough that refusing them would be too strict).  Parser must
	// accept both CRLF and LF.
	content := []byte("Manifest-Version: 1.0\nImplementation-Title: Foo\nImplementation-Version: 2.0\n")
	got, err := parseManifest(content)
	if err != nil {
		t.Fatalf("parseManifest: %v", err)
	}
	if got.ImplementationTitle != "Foo" || got.ImplementationVersion != "2.0" {
		t.Errorf("LF-only parse failed: %+v", got)
	}
}

func TestParseManifest_ExceedsSizeCap(t *testing.T) {
	// A MANIFEST.MF larger than maxManifestBytes must fail rather than
	// consume unbounded memory.
	big := []byte("Manifest-Version: 1.0\r\nJunk: " + strings.Repeat("x", maxManifestBytes+1) + "\r\n")
	_, err := parseManifest(big)
	if err == nil {
		t.Fatalf("expected error on oversized manifest, got nil")
	}
}

// ---------------------------------------------------------------------------
// parseFilename — <artifact>-<version>.jar fallback
// ---------------------------------------------------------------------------

func TestParseFilename(t *testing.T) {
	cases := []struct {
		in                 string
		wantArtifact, wantV string
	}{
		// Simple happy path.
		{"commons-lang3-3.12.0.jar", "commons-lang3", "3.12.0"},
		// Version with qualifier suffix.
		{"spring-boot-2.7.18-RELEASE.jar", "spring-boot", "2.7.18-RELEASE"},
		// No hyphen at all — whole base is the artifact, no version.
		{"tools.jar", "tools", ""},
		// Hyphen but no digit suffix — don't guess a version that isn't there.
		{"nothing-like-a-version.jar", "nothing-like-a-version", ""},
		// Multiple numeric segments; version splits at the last hyphen
		// whose suffix starts with a digit.
		{"my-project-utils-2.1.0.jar", "my-project-utils", "2.1.0"},
		// Snapshot convention — version includes -SNAPSHOT.
		{"lib-1.0-SNAPSHOT.jar", "lib", "1.0-SNAPSHOT"},
		// Uppercase doesn't matter for splitting.
		{"Foo-Bar-1.2.jar", "Foo-Bar", "1.2"},
		// Not a .jar — caller shouldn't hand this to us but be defensive.
		{"weird.txt", "", ""},
	}
	for _, tc := range cases {
		t.Run(tc.in, func(t *testing.T) {
			gotA, gotV := parseFilename(tc.in)
			if gotA != tc.wantArtifact || gotV != tc.wantV {
				t.Errorf("parseFilename(%q) = (%q, %q); want (%q, %q)",
					tc.in, gotA, gotV, tc.wantArtifact, tc.wantV)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// extractFromJar — the top-level integration
// ---------------------------------------------------------------------------

func TestExtractFromJar_PomPropertiesWins(t *testing.T) {
	// When a JAR has pom.properties AND a MANIFEST.MF, pom.properties
	// takes precedence: it's the Maven-authoritative source.
	jar := buildJAR(t, map[string][]byte{
		"META-INF/maven/org.example/widget/pom.properties": []byte(
			"groupId=org.example\nartifactId=widget\nversion=1.0\n",
		),
		"META-INF/MANIFEST.MF": []byte(
			"Manifest-Version: 1.0\r\n" +
				"Implementation-Title: Widget\r\n" +
				"Implementation-Version: 999.0\r\n",
		),
	})

	records, errs := extractFromJar(jar)
	if len(errs) > 0 {
		t.Fatalf("unexpected errors: %+v", errs)
	}
	if len(records) != 1 {
		t.Fatalf("expected 1 record, got %d", len(records))
	}
	got := records[0]
	if got.Name != "org.example:widget" {
		t.Errorf("Name: got %q want org.example:widget", got.Name)
	}
	if got.Version != "1.0" {
		t.Errorf("Version: got %q want 1.0", got.Version)
	}
	if got.EnvType != EnvJVM {
		t.Errorf("EnvType: got %q want %q", got.EnvType, EnvJVM)
	}
}

func TestExtractFromJar_ShadedUberJarMultipleCoordinates(t *testing.T) {
	// An uber-jar bundles multiple Maven artefacts; each has its own
	// pom.properties under META-INF/maven/<group>/<artifact>/.  We must
	// emit one PackageRecord per embedded coordinate, not merge them.
	// This is the key differentiator vs manifest-only tools that see
	// the uber-jar as a single artefact.
	jar := buildJAR(t, map[string][]byte{
		"META-INF/maven/org.a/lib-a/pom.properties": []byte("groupId=org.a\nartifactId=lib-a\nversion=1.0\n"),
		"META-INF/maven/org.b/lib-b/pom.properties": []byte("groupId=org.b\nartifactId=lib-b\nversion=2.0\n"),
		"META-INF/maven/org.c/lib-c/pom.properties": []byte("groupId=org.c\nartifactId=lib-c\nversion=3.0\n"),
	})

	records, _ := extractFromJar(jar)
	if len(records) != 3 {
		t.Fatalf("expected 3 records (one per embedded coordinate), got %d", len(records))
	}
	names := map[string]string{}
	for _, r := range records {
		names[r.Name] = r.Version
	}
	if names["org.a:lib-a"] != "1.0" || names["org.b:lib-b"] != "2.0" || names["org.c:lib-c"] != "3.0" {
		t.Errorf("shaded coordinates not all extracted correctly: %+v", names)
	}
}

func TestExtractFromJar_ManifestFallbackWhenNoPomProperties(t *testing.T) {
	// Some JARs (notably OSGi bundles from the Eclipse p2 tooling) have
	// a MANIFEST.MF but no META-INF/maven directory.  We fall back to
	// OSGi Bundle-* headers; Implementation-* is the next fallback.
	jar := buildJAR(t, map[string][]byte{
		"META-INF/MANIFEST.MF": []byte(
			"Manifest-Version: 1.0\r\n" +
				"Bundle-SymbolicName: org.eclipse.core.runtime\r\n" +
				"Bundle-Version: 3.26.100\r\n",
		),
	})

	records, errs := extractFromJar(jar)
	if len(errs) > 0 {
		t.Fatalf("unexpected errors: %+v", errs)
	}
	if len(records) != 1 {
		t.Fatalf("expected 1 record, got %d", len(records))
	}
	if records[0].Name != "org.eclipse.core.runtime" {
		t.Errorf("Name: got %q want org.eclipse.core.runtime", records[0].Name)
	}
	if records[0].Version != "3.26.100" {
		t.Errorf("Version: got %q want 3.26.100", records[0].Version)
	}
}

func TestExtractFromJar_FilenameFallbackLastResort(t *testing.T) {
	// No pom.properties, no MANIFEST.MF — the filename is the last
	// resort.  We still emit a record (otherwise the CVE-correlation
	// layer misses this library entirely) but the caller can detect
	// the heuristic source if they care (future: add a Source field).
	jar := buildJAR(t, nil)
	// buildJAR wrote to <tmp>/fixture.jar; we can't rename cheaply
	// across filesystems, so verify the filename extractor independently
	// in parseFilename tests above — here just assert we get SOMETHING
	// rather than empty output.
	records, _ := extractFromJar(jar)
	if len(records) != 1 {
		t.Fatalf("expected 1 filename-fallback record, got %d", len(records))
	}
	if records[0].Name == "" {
		t.Errorf("expected non-empty Name from filename fallback")
	}
}

func TestExtractFromJar_CorruptedZip(t *testing.T) {
	// A corrupt/truncated JAR must produce a ScanError, not a panic.
	// Write a few bytes of garbage and pass that path.
	tmp := t.TempDir() + "/garbage.jar"
	if err := os.WriteFile(tmp, []byte("not-a-zip-file"), 0o644); err != nil {
		t.Fatalf("write garbage file: %v", err)
	}
	records, errs := extractFromJar(tmp)
	if len(errs) == 0 {
		t.Errorf("expected a ScanError for corrupt JAR")
	}
	if len(records) != 0 {
		t.Errorf("expected no records for corrupt JAR, got %d", len(records))
	}
}

func TestExtractFromJar_ZipSlipAttackIgnored(t *testing.T) {
	// A malicious JAR might name an entry "../../../etc/passwd" trying
	// to escape a naive extractor.  We don't extract — we only read
	// specific files by their logical path.  Verify the malicious
	// filename doesn't hand us bogus metadata from an unrelated host
	// file, and doesn't cause the parser to misbehave.
	jar := buildJAR(t, map[string][]byte{
		"../../../etc/passwd":                         []byte("root:x:0:0:root:/root:/bin/bash\n"),
		"META-INF/maven/o/a/pom.properties":           []byte("groupId=o\nartifactId=a\nversion=1\n"),
	})
	records, _ := extractFromJar(jar)
	// The pom.properties we planted must parse; the zip-slip entry
	// must be ignored by the iteration (we only look at entries whose
	// logical path matches our patterns).
	if len(records) != 1 || records[0].Name != "o:a" {
		t.Errorf("zip-slip attack may have corrupted extraction: %+v", records)
	}
}

