// Sentari-managed marker rendering.
//
// Every config file the agent writes begins with a marker comment
// that identifies it as Sentari-managed and embeds the policy-map
// version + signing key_id + apply timestamp.  Operators inspecting
// a host's ``pip.conf`` need three things at a glance:
//
//  1. *That* this is Sentari-managed (so they don't hand-edit and
//     have it overwritten 30 minutes later).
//  2. *Which* policy-map version was last applied (drift detection
//     during incident review).
//  3. *When* it was applied (cross-reference with the agent log).
//
// The marker is rendered per file format — pip / npm / apt / yum
// use shell-style ``#`` comments; Maven and NuGet use XML
// ``<!-- -->``.  Generated by the per-ecosystem writers via the
// helpers below.

package installgate

import (
	"fmt"
	"strings"
	"time"
)

// renderHashMarker produces the two-line ``#``-prefixed comment
// block used by pip / npm / apt / yum config files.  Format intent:
//
//	# Managed by Sentari (version=1730901234, signed=primary, applied=2026-04-25T10:00:00Z)
//	# Do not edit manually — changes are overwritten on the next policy sync.
//
// The trailing ``\n`` is included so callers can concatenate the
// rendered config body without worrying about leading whitespace.
//
// XML-flavoured marker for ``settings.xml`` / ``NuGet.Config``
// lands with the maven + nuget writers in a follow-up PR.
func renderHashMarker(fields MarkerFields) string {
	return strings.Join([]string{
		fmt.Sprintf(
			"# Managed by Sentari (version=%d, signed=%s, applied=%s)",
			fields.Version,
			fields.KeyID,
			fields.Applied.UTC().Format(time.RFC3339),
		),
		"# Do not edit manually — changes are overwritten on the next policy sync.",
		"",
	}, "\n")
}
