// Sentari-managed marker rendering.
//
// Every config file the agent writes begins with a marker comment
// that identifies it as Sentari-managed and embeds the policy-map
// version + signing key_id + apply timestamp.  Operators inspecting
// a host's ``pip.conf`` need three things at a glance:
//
//  1. *That* this is Sentari-managed (so they don't hand-edit and
//     have it overwritten 30 minutes later).
//  2. *Which* policy-map version was last applied (drift detection
//     during incident review).
//  3. *When* it was applied (cross-reference with the agent log).
//
// The marker is rendered per file format — pip / npm / apt / yum
// use shell-style ``#`` comments; Maven and NuGet use XML
// ``<!-- -->``.  Generated by the per-ecosystem writers via the
// helpers below.

package installgate

import (
	"fmt"
	"strings"
	"time"
)

// validateMarkerKeyID refuses KeyIDs that would land in an XML
// comment as ill-formed content (XML disallows ``--`` inside
// comments and disallows comments ending in ``-``).  Even the
// hash-marker variant routes through this so a misconfigured
// KeyID can't smuggle a newline / control byte into pip's
// ``signed=...`` line — defence-in-depth, the server-side
// validator already guards against most of this.
//
// Returns nil on a clean KeyID; ``error`` describes the offending
// character / sequence so an operator chasing a render failure
// can correct the server-side configuration.
func validateMarkerKeyID(keyID string) error {
	if keyID == "" {
		return fmt.Errorf("marker key_id is empty")
	}
	for i := 0; i < len(keyID); i++ {
		c := keyID[i]
		if c < 0x20 || c == 0x7F {
			return fmt.Errorf("marker key_id contains forbidden control byte 0x%02x at offset %d", c, i)
		}
	}
	if strings.Contains(keyID, "--") {
		return fmt.Errorf("marker key_id contains ``--`` (illegal in XML comments)")
	}
	if strings.HasSuffix(keyID, "-") {
		return fmt.Errorf("marker key_id ends with ``-`` (illegal in XML comments)")
	}
	return nil
}

// renderHashMarker produces the two-line ``#``-prefixed comment
// block used by pip / npm / apt / yum config files.  Format intent:
//
//	# Managed by Sentari (version=1730901234, signed=primary, applied=2026-04-25T10:00:00Z)
//	# Do not edit manually — changes are overwritten on the next policy sync.
//
// The trailing ``\n`` is included so callers can concatenate the
// rendered config body without worrying about leading whitespace.
func renderHashMarker(fields MarkerFields) string {
	return strings.Join([]string{
		fmt.Sprintf(
			"# Managed by Sentari (version=%d, signed=%s, applied=%s)",
			fields.Version,
			fields.KeyID,
			fields.Applied.UTC().Format(time.RFC3339),
		),
		"# Do not edit manually — changes are overwritten on the next policy sync.",
		"",
	}, "\n")
}

// renderXMLMarker produces the XML-comment variant for
// ``settings.xml`` / ``NuGet.Config``.  Used by the Maven writer
// (PR-5) and the NuGet writer (PR-6).  Format intent:
//
//	<!-- Managed by Sentari (version=..., signed=..., applied=...) -->
//
// Single-line so it can sit between the XML declaration and the
// document's root element without disrupting parsers that have
// strict-DTD expectations.  isSentariManaged matches the
// ``<!-- Managed by Sentari`` prefix to identify these files
// without rendering — same recognition pattern as the hash
// marker, just XML-flavoured.
func renderXMLMarker(fields MarkerFields) string {
	return fmt.Sprintf(
		"<!-- Managed by Sentari (version=%d, signed=%s, applied=%s) -->\n",
		fields.Version,
		fields.KeyID,
		fields.Applied.UTC().Format(time.RFC3339),
	)
}

// renderSlashMarker produces the ``//``-prefixed comment block
// used by Groovy / Java / sbt-style configs where ``#`` is not a
// comment.  Format intent:
//
//	// Managed by Sentari (version=..., signed=..., applied=...)
//	// Do not edit manually — changes are overwritten on the next policy sync.
//
// Trailing ``\n`` so callers can concatenate the rendered config
// body without leading-whitespace gymnastics — same shape as
// renderHashMarker.  isSentariManaged recognises the
// ``// Managed by Sentari`` substring anywhere in the first 1 KiB.
func renderSlashMarker(fields MarkerFields) string {
	return strings.Join([]string{
		fmt.Sprintf(
			"// Managed by Sentari (version=%d, signed=%s, applied=%s)",
			fields.Version,
			fields.KeyID,
			fields.Applied.UTC().Format(time.RFC3339),
		),
		"// Do not edit manually — changes are overwritten on the next policy sync.",
		"",
	}, "\n")
}
