package deptree

import (
	"os"
	"path/filepath"
	"testing"
)

// TestParseYarnLock_berryReturnsNil proves a yarn v2+/berry lockfile
// (which opens with a `__metadata:` block) is NOT misparsed by the v1
// parser: ParseYarnLock returns (nil, nil) rather than emitting garbage
// edges from a format it cannot read.
func TestParseYarnLock_berryReturnsNil(t *testing.T) {
	dir := t.TempDir()
	yarnPath := filepath.Join(dir, "yarn.lock")
	pjPath := filepath.Join(dir, "package.json")
	if err := os.WriteFile(yarnPath, []byte(`# generated by yarn

__metadata:
  version: 8
  cacheKey: 10c0

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  dependencies:
    foo: "npm:^1.0.0"
`), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(pjPath, []byte(`{"name":"app","version":"1.0.0","dependencies":{"lodash":"^4.17.21"}}`), 0o600); err != nil {
		t.Fatal(err)
	}
	edges, err := ParseYarnLock(yarnPath, pjPath)
	if err != nil {
		t.Fatalf("expected nil error for berry lockfile, got %v", err)
	}
	if edges != nil {
		t.Fatalf("expected nil edges for berry lockfile (v1 parser must not run), got %+v", edges)
	}
}

func TestParseYarnLock_direct_and_transitive(t *testing.T) {
	dir := filepath.Join("testdata", "npm", "yarn-v1")
	edges, err := ParseYarnLock(filepath.Join(dir, "yarn.lock"), filepath.Join(dir, "package.json"))
	if err != nil {
		t.Fatalf("parse failed: %v", err)
	}
	if len(edges) != 3 {
		t.Fatalf("expected 3 edges (2 direct + 1 transitive), got %d: %+v", len(edges), edges)
	}

	byChild := map[string]DepEdge{}
	for _, e := range edges {
		byChild[e.ChildName] = e
	}

	expressEdge, ok := byChild["express"]
	if !ok || expressEdge.Type != "direct" || expressEdge.ChildVersion != "4.18.2" || expressEdge.ParentName != "yarn-v1-fixture" {
		t.Errorf("express edge wrong: %+v", expressEdge)
	}
	if expressEdge.Depth != 1 || len(expressEdge.IntroducedByPath) != 2 {
		t.Errorf("express depth/path wrong: depth=%d path=%v", expressEdge.Depth, expressEdge.IntroducedByPath)
	}

	lodashEdge, ok := byChild["lodash"]
	if !ok || lodashEdge.Type != "direct" {
		t.Errorf("lodash edge wrong: %+v", lodashEdge)
	}

	qsEdge, ok := byChild["qs"]
	if !ok || qsEdge.Type != "transitive" || qsEdge.ChildVersion != "6.11.0" || qsEdge.ParentName != "express" || qsEdge.Depth != 2 {
		t.Errorf("qs edge wrong: %+v", qsEdge)
	}
}

// TestParseYarnLock_multiParentSharedTransitive proves each transitive
// edge's introduced_by_path is resolved PER EMITTING PARENT, not from a
// single child-keyed global BFS result.
//
// Fixture: root depends on both `a` and `c`; a→shared@1.0.0 and
// c→shared@1.0.0, where `shared` is NOT a root dependency. BFS stores
// shared's path once (via whichever parent it reached first). The buggy
// parser emitted the c→shared edge with that stored path [root,a,shared]
// — a chain that never traverses c, violating path[len-2]==parent. The
// fix anchors every edge on its own parent's path, so a→shared carries
// [root,a,shared] and c→shared carries [root,c,shared].
func TestParseYarnLock_multiParentSharedTransitive(t *testing.T) {
	dir := t.TempDir()
	yarnPath := filepath.Join(dir, "yarn.lock")
	pjPath := filepath.Join(dir, "package.json")
	if err := os.WriteFile(yarnPath, []byte(`# yarn lockfile v1

a@^1.0.0:
  version "1.0.0"
  dependencies:
    shared "^1.0.0"

c@^1.0.0:
  version "1.0.0"
  dependencies:
    shared "^1.0.0"

shared@^1.0.0:
  version "1.0.0"
`), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(pjPath, []byte(`{"name":"multiparent-fixture","version":"1.0.0","dependencies":{"a":"^1.0.0","c":"^1.0.0"}}`), 0o600); err != nil {
		t.Fatal(err)
	}
	edges, err := ParseYarnLock(yarnPath, pjPath)
	if err != nil {
		t.Fatalf("parse failed: %v", err)
	}

	// Every edge must satisfy the shared contract invariants, including
	// path[len-2]==parent for BOTH shared edges.
	assertEdgeContractInvariants(t, edges, "yarn-multiparent")

	type key struct{ parent, child string }
	byEdge := map[key]DepEdge{}
	for _, e := range edges {
		byEdge[key{e.ParentName, e.ChildName}] = e
	}
	root := "multiparent-fixture"

	pathEq := func(got, want []string) bool {
		if len(got) != len(want) {
			return false
		}
		for i := range got {
			if got[i] != want[i] {
				return false
			}
		}
		return true
	}

	aShared, ok := byEdge[key{"a", "shared"}]
	if !ok {
		t.Fatalf("a->shared edge missing; edges=%+v", edges)
	}
	if aShared.Type != "transitive" || aShared.Depth != 2 || !pathEq(aShared.IntroducedByPath, []string{root, "a", "shared"}) {
		t.Errorf("a->shared edge wrong: %+v (want path [%s a shared] depth 2)", aShared, root)
	}

	cShared, ok := byEdge[key{"c", "shared"}]
	if !ok {
		t.Fatalf("c->shared edge missing; edges=%+v", edges)
	}
	if cShared.Type != "transitive" || cShared.Depth != 2 || !pathEq(cShared.IntroducedByPath, []string{root, "c", "shared"}) {
		t.Errorf("c->shared edge wrong: %+v (want path [%s c shared] depth 2)", cShared, root)
	}
}

func TestYarnSpecName(t *testing.T) {
	cases := map[string]string{
		"lodash@^4.17.0":    "lodash",
		"@types/node@^18.0": "@types/node",
		"foo@1.0.0":         "foo",
	}
	for in, want := range cases {
		if got := yarnSpecName(in); got != want {
			t.Errorf("yarnSpecName(%q) = %q, want %q", in, got, want)
		}
	}
}
