package deptree

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

// Fuzz targets for the dep-graph lockfile parsers.
//
// Both parsers read attacker-influenceable files off the local filesystem
// (a yarn.lock / requirements.txt sitting in a scanned project tree), so any
// panic, hang, or contract violation is a direct hit on the scan cycle — a
// single malformed lockfile in a shared repo could freeze the daemon for every
// host on a fleet, or emit dep-edges the server's v3 ingest path rejects.
//
// Each target asserts two things on every input:
//   - the parser never panics (the fuzz harness catches panics as failures);
//   - every emitted DepEdge satisfies the STRUCTURAL half of the v3 per-edge
//     contract that must hold on ANY input (assertEdgeStructInvariants below):
//     introduced_by_path has >=2 nodes, depth==len(introduced_by_path)-1, and
//     the path ends …→parent→child. These are exactly the facts the server's
//     v3 ingest path relies on regardless of lockfile shape.
//
// The tighter direct⟹depth==1 / transitive⟹depth>=2 coupling from
// assertEdgeContractInvariants is deliberately NOT asserted here: it only holds
// when directness is establishable, and ParseYarnLock documents that it tags
// EVERY edge "transitive" when the sibling package.json is missing/unusable —
// which then legitimately yields a transitive-tagged depth-1 root edge on
// pathological fuzz inputs. That is expected behavior, not a contract breach.
//
// Run in CI: go test -run=^$ -fuzz=FuzzParseYarnV1 -fuzztime=15s ./scanner/deptree/
//            go test -run=^$ -fuzz=FuzzParseRequirementsTxt -fuzztime=15s ./scanner/deptree/

// assertEdgeStructInvariants checks the always-true structural half of the v3
// per-edge contract — the invariants that must hold for every emitted edge on
// any input, malformed or not, because the server ingests them verbatim.
func assertEdgeStructInvariants(t *testing.T, edges []DepEdge, label string) {
	t.Helper()
	for _, e := range edges {
		n := len(e.IntroducedByPath)
		if n < 2 {
			t.Errorf("%s: edge %s->%s has introduced_by_path with <2 nodes: %v",
				label, e.ParentName, e.ChildName, e.IntroducedByPath)
			continue
		}
		if want := n - 1; e.Depth != want {
			t.Errorf("%s: edge %s->%s has depth=%d but path has %d nodes (want depth=%d): %v",
				label, e.ParentName, e.ChildName, e.Depth, n, want, e.IntroducedByPath)
		}
		if e.IntroducedByPath[n-1] != e.ChildName {
			t.Errorf("%s: edge %s->%s path must end at child, got %v",
				label, e.ParentName, e.ChildName, e.IntroducedByPath)
		}
		if e.IntroducedByPath[n-2] != e.ParentName {
			t.Errorf("%s: edge %s->%s path[len-2] must be the parent, got %v",
				label, e.ParentName, e.ChildName, e.IntroducedByPath)
		}
	}
}

// FuzzParseYarnV1 exercises the exported yarn.lock v1 parser end-to-end
// (ParseYarnLock), driving both the lockfile bytes and the sibling
// package.json that supplies the direct/transitive partition. Malformed,
// truncated, and berry-shaped inputs must all terminate without panicking and
// yield only contract-valid edges.
func FuzzParseYarnV1(f *testing.F) {
	// Seed 1: the canonical v1 fixture (direct + transitive).
	f.Add(`# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


express@^4.18.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"
  integrity sha512-test
  dependencies:
    qs "6.11.0"

qs@6.11.0:
  version "6.11.0"
  resolved "https://registry.yarnpkg.com/qs/-/qs-6.11.0.tgz"
  integrity sha512-test

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-test
`, `{"name":"yarn-v1-fixture","version":"1.0.0","dependencies":{"express":"^4.18.0","lodash":"^4.17.21"}}`)
	// Seed 2: berry-shaped lockfile (must bail cleanly, no edges).
	f.Add("__metadata:\n  version: 8\n\n\"express@npm:^4.18.0\":\n  version: 4.18.2\n", `{"dependencies":{"express":"^4.18.0"}}`)
	// Seed 3: empty inputs.
	f.Add("", "")
	// Seed 4: optionalDependencies block + malformed package.json.
	f.Add("express@^4.18.0:\n  version \"4.18.2\"\n  optionalDependencies:\n    fsevents \"2.3.2\"\n", "{not json")
	// Seed 5: garbage / structural edge cases.
	f.Add("::::\n  version\n    \n@@@@", "{}")

	f.Fuzz(func(t *testing.T, yarnRaw, pkgJSONRaw string) {
		dir := t.TempDir()
		yarnPath := filepath.Join(dir, "yarn.lock")
		pjPath := filepath.Join(dir, "package.json")
		if err := os.WriteFile(yarnPath, []byte(yarnRaw), 0o600); err != nil {
			t.Skip(err)
		}
		if err := os.WriteFile(pjPath, []byte(pkgJSONRaw), 0o600); err != nil {
			t.Skip(err)
		}

		edges, err := ParseYarnLock(yarnPath, pjPath)
		if err != nil {
			// A returned error is an acceptable outcome for malformed input;
			// what matters is that we neither panicked nor produced edges.
			return
		}
		assertEdgeStructInvariants(t, edges, "fuzz-yarn")
	})
}

// FuzzParseRequirementsTxt exercises the PEP 440 requirements.txt parser
// (ParseRequirementsTxt). Arbitrary bytes reach it via a requirements.txt in a
// scanned project; the parser must tolerate any specifier soup, BOMs, comments,
// and control bytes without panicking, and every emitted edge must be
// contract-valid.
func FuzzParseRequirementsTxt(f *testing.F) {
	f.Add(`# Project requirements
requests==2.31.0
urllib3==2.0.7  # also pinned
-r dev-requirements.txt`)
	f.Add(`requests==2.31.0
urllib3>=1.26
flask[async]>=2.0
django~=4.2.0
boto3!=1.34.0
mypkg===1.0.0+local
bare-name
psycopg2-binary>=2.9 ; python_version >= "3.8"
--hash=sha256:abc123`)
	f.Add("")
	f.Add("\xef\xbb\xbfrequests==2.31.0\n") // leading UTF-8 BOM
	f.Add("\x00\x01\x02 ==\n[extras]\n===\n;;;;")
	f.Add("a==")

	f.Fuzz(func(t *testing.T, raw string) {
		dir := t.TempDir()
		path := filepath.Join(dir, "requirements.txt")
		if err := os.WriteFile(path, []byte(raw), 0o600); err != nil {
			t.Skip(err)
		}

		edges, err := ParseRequirementsTxt(path)
		if err != nil {
			return
		}
		assertEdgeStructInvariants(t, edges, "fuzz-requirements")
	})
}

// FuzzParseNpmPackageLock exercises the exported package-lock.json parser
// (ParseNpmPackageLock) — the single most-exposed lockfile parser, since a
// package-lock.json sits at the root of essentially every scanned Node project.
// Arbitrary bytes reach it via that file; malformed, truncated, v1-shaped, and
// deeply-nested inputs must all terminate without panicking, and every emitted
// edge must satisfy the structural half of the v3 per-edge contract.
func FuzzParseNpmPackageLock(f *testing.F) {
	// Seed 1: canonical v3 lockfile (root + one direct dep).
	f.Add(`{
  "name": "seed-app",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": {
      "name": "seed-app",
      "version": "1.0.0",
      "dependencies": { "lodash": "^4.17.21" }
    },
    "node_modules/lodash": { "version": "4.17.21", "license": "MIT" }
  }
}`)
	// Seed 2: v2 with a transitive dep + a dev dep at root.
	f.Add(`{
  "name": "seed-v2",
  "version": "2.0.0",
  "lockfileVersion": 2,
  "packages": {
    "": {
      "name": "seed-v2",
      "version": "2.0.0",
      "dependencies": { "express": "^4.18.0" },
      "devDependencies": { "jest": "^29.0.0" }
    },
    "node_modules/express": { "version": "4.18.2", "dependencies": { "qs": "6.11.0" } },
    "node_modules/qs": { "version": "6.11.0" },
    "node_modules/jest": { "version": "29.7.0", "dev": true }
  }
}`)
	// Seed 3: unsupported v1 lockfile shape (must error cleanly, no edges).
	f.Add(`{"name":"old","version":"1.0.0","lockfileVersion":1,"dependencies":{"lodash":{"version":"4.17.21"}}}`)
	// Seed 4: empty object / missing packages.
	f.Add(`{}`)
	// Seed 5: malformed JSON / structural garbage.
	f.Add(`{"lockfileVersion":3,"packages":{"":`)
	f.Add(``)

	f.Fuzz(func(t *testing.T, lockRaw string) {
		dir := t.TempDir()
		lockPath := filepath.Join(dir, "package-lock.json")
		if err := os.WriteFile(lockPath, []byte(lockRaw), 0o600); err != nil {
			t.Skip(err)
		}

		edges, err := ParseNpmPackageLock(lockPath)
		if err != nil {
			// A returned error is an acceptable outcome for malformed or
			// unsupported (v1) input; what matters is no panic and no
			// contract-violating edges.
			return
		}
		assertEdgeStructInvariants(t, edges, "fuzz-npm-package-lock")
	})
}

// FuzzParseMavenPom exercises the exported pom.xml parser (ParseMavenPom) — the
// other most-exposed manifest, sitting at the root of every scanned Maven/
// Gradle-with-pom project and reachable with attacker-influenceable bytes. The
// XML decoder, ${property} interpolation, and <parent>/<dependencyManagement>
// resolution must tolerate any XML soup, entity tricks, and truncation without
// panicking or hanging. m2Dir points at an empty temp dir so transitive
// resolution takes its best-effort/unresolved path; every emitted edge must
// still satisfy the structural per-edge contract.
func FuzzParseMavenPom(f *testing.F) {
	// Seed 1: canonical single-dependency POM.
	f.Add(`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example.app</groupId>
    <artifactId>my-app</artifactId>
    <version>1.0.0</version>
    <dependencies>
        <dependency>
            <groupId>com.example</groupId>
            <artifactId>lib-a</artifactId>
            <version>1.0.0</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>`)
	// Seed 2: coordinate inherited from <parent> + a ${property} version.
	f.Add(`<?xml version="1.0"?>
<project>
  <parent>
    <groupId>com.example</groupId>
    <version>2.0.0</version>
  </parent>
  <artifactId>child</artifactId>
  <properties><dep.version>3.1.4</dep.version></properties>
  <dependencies>
    <dependency>
      <groupId>org.foo</groupId>
      <artifactId>bar</artifactId>
      <version>${dep.version}</version>
    </dependency>
  </dependencies>
</project>`)
	// Seed 3: test/provided scopes (skipped by the parser) + no version.
	f.Add(`<project><artifactId>x</artifactId><dependencies>` +
		`<dependency><groupId>g</groupId><artifactId>a</artifactId><scope>test</scope></dependency>` +
		`</dependencies></project>`)
	// Seed 4: empty / structurally-degenerate inputs.
	f.Add(`<project></project>`)
	f.Add(`<project><dependencies>`)
	f.Add(``)

	f.Fuzz(func(t *testing.T, pomRaw string) {
		dir := t.TempDir()
		pomPath := filepath.Join(dir, "pom.xml")
		if err := os.WriteFile(pomPath, []byte(pomRaw), 0o600); err != nil {
			t.Skip(err)
		}
		// Empty m2 dir: no local repository, so the resolver stays on its
		// best-effort/unresolved path rather than reading real artifacts.
		m2Dir := filepath.Join(dir, "m2")

		edges, err := ParseMavenPom(context.Background(), pomPath, m2Dir)
		if err != nil {
			// Malformed XML is an acceptable error outcome; assert only that
			// we neither panicked nor emitted contract-violating edges.
			return
		}
		assertEdgeStructInvariants(t, edges, "fuzz-maven-pom")
	})
}

// FuzzParsePnpmLock exercises the exported pnpm-lock.yaml parser
// (ParsePnpmLock). A pnpm-lock.yaml sits at the root of every scanned pnpm
// project, so arbitrary bytes reach the YAML decoder, the importers/snapshots/
// packages BFS, and the pnpmKeyParts key-splitting heuristics. Malformed,
// truncated, wrong-typed, workspace-shaped, and deeply-nested inputs must all
// terminate without panicking, and every emitted edge must satisfy the
// structural half of the v3 per-edge contract.
func FuzzParsePnpmLock(f *testing.F) {
	// Seed 1: canonical v6 lockfile (root direct + one transitive).
	f.Add(`lockfileVersion: '6.0'

importers:

  .:
    dependencies:
      express:
        specifier: ^4.18.0
        version: 4.18.2

packages:

  /express@4.18.2:
    resolution: {integrity: sha512-test}
    dependencies:
      qs: 6.11.0

  /qs@6.11.0:
    resolution: {integrity: sha512-test}
`)
	// Seed 2: pnpm >=9 snapshots layout (deps live under snapshots:).
	f.Add(`lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      express:
        specifier: ^4.18.0
        version: 4.18.2
packages:
  express@4.18.2:
    resolution: {integrity: sha512-test}
snapshots:
  express@4.18.2:
    dependencies:
      qs: 6.11.0
  qs@6.11.0: {}
`)
	// Seed 3: pnpm 5.x '/'-separated keys (no version '@').
	f.Add("lockfileVersion: 5.4\ndependencies:\n  express: 4.18.2\npackages:\n  /express/4.18.2:\n    dependencies:\n      qs: 6.11.0\n  /qs/6.11.0: {}\n")
	// Seed 4: workspace with a non-root importer member.
	f.Add("importers:\n  .:\n    devDependencies:\n      typescript:\n        specifier: ^5.0.0\n        version: 5.4.5\n  packages/api:\n    dependencies:\n      express:\n        specifier: ^4.0.0\n        version: 4.18.2\n")
	// Seed 5: structurally-degenerate / empty inputs.
	f.Add("{}")
	f.Add("")
	f.Add("importers:\n  .:\n    dependencies: notamap\n")

	f.Fuzz(func(t *testing.T, lockRaw string) {
		dir := t.TempDir()
		lockPath := filepath.Join(dir, "pnpm-lock.yaml")
		if err := os.WriteFile(lockPath, []byte(lockRaw), 0o600); err != nil {
			t.Skip(err)
		}

		edges, err := ParsePnpmLock(lockPath)
		if err != nil {
			// A returned error is an acceptable outcome for malformed input;
			// what matters is no panic and no contract-violating edges.
			return
		}
		assertEdgeStructInvariants(t, edges, "fuzz-pnpm-lock")
	})
}

// FuzzParseNuGetProjectAssets exercises the exported project.assets.json parser
// (ParseNuGetProjectAssets) — the file `dotnet restore` writes at the root of
// every scanned .NET project. Arbitrary bytes reach the JSON decoder, the
// TFM-normalization, and the per-target BFS. Malformed, truncated, wrong-typed,
// slash-less-key, and deeply-nested inputs must all terminate without panicking,
// and every emitted edge must satisfy the structural half of the v3 per-edge
// contract.
func FuzzParseNuGetProjectAssets(f *testing.F) {
	// Seed 1: canonical assets file (short-TFM keyed, 1 direct + 1 transitive).
	f.Add(`{
  "version": 3,
  "targets": {
    "net6.0": {
      "Newtonsoft.Json/13.0.3": {
        "type": "package",
        "dependencies": { "Microsoft.CSharp": "4.7.0" }
      },
      "Microsoft.CSharp/4.7.0": { "type": "package" }
    }
  },
  "project": {
    "version": "1.0.0",
    "restore": { "projectName": "MyNetApp" },
    "frameworks": {
      "net6.0": { "dependencies": { "Newtonsoft.Json": { "version": "[13.0.3, )" } } }
    }
  }
}`)
	// Seed 2: real long-moniker target key with a "/<rid>" suffix.
	f.Add(`{"targets":{".NETCoreApp,Version=v6.0/win-x64":{"Serilog/2.12.0":{"type":"package"}}},` +
		`"project":{"restore":{"projectName":"RealNetApp"},"frameworks":{"net6.0":{"dependencies":{"Serilog":{"version":"2.12.0"}}}}}}`)
	// Seed 3: empty object / missing targets.
	f.Add(`{}`)
	// Seed 4: wrong-typed / malformed / structural garbage.
	f.Add(`{"targets":{"net6.0":{"NoSlashKey":{"type":"package"}}}}`)
	f.Add(`{"targets":"nope"}`)
	f.Add(`{"targets":{"net6.0":`)
	f.Add(``)

	f.Fuzz(func(t *testing.T, assetsRaw string) {
		dir := t.TempDir()
		assetsPath := filepath.Join(dir, "project.assets.json")
		if err := os.WriteFile(assetsPath, []byte(assetsRaw), 0o600); err != nil {
			t.Skip(err)
		}

		edges, err := ParseNuGetProjectAssets(assetsPath)
		if err != nil {
			// A returned error is an acceptable outcome for malformed or
			// unsupported input; what matters is no panic and no
			// contract-violating edges.
			return
		}
		assertEdgeStructInvariants(t, edges, "fuzz-nuget-project-assets")
	})
}

// FuzzParseUvLock exercises the exported uv.lock parser (ParseUvLock). A
// uv.lock (TOML) sits at the root of every scanned uv/PEP 621 project, so
// arbitrary bytes reach the TOML decoder, the [[package]] / [[package.
// dependencies]] walk, the PEP 503 name normalization, and the
// no-incoming-edge root inference. Malformed, truncated, cyclic, and
// wrong-typed inputs must all terminate without panicking, and every emitted
// edge must satisfy the structural half of the v3 per-edge contract.
func FuzzParseUvLock(f *testing.F) {
	// Seed 1: canonical fixture (root myapp -> requests -> urllib3).
	f.Add(`version = 1

[[package]]
name = "myapp"
version = "0.1.0"

[[package.dependencies]]
name = "requests"

[[package]]
name = "requests"
version = "2.31.0"

[[package.dependencies]]
name = "urllib3"

[[package]]
name = "urllib3"
version = "2.0.7"
`)
	// Seed 2: non-normalized dep name that must PEP 503-join.
	f.Add("[[package]]\nname = \"app\"\nversion = \"1.0\"\n[[package.dependencies]]\nname = \"Typing_Extensions\"\n[[package]]\nname = \"typing-extensions\"\nversion = \"4.9.0\"\n")
	// Seed 3: pure cycle (no derivable root -> nil edges).
	f.Add("[[package]]\nname = \"a\"\nversion = \"1\"\n[[package.dependencies]]\nname = \"b\"\n[[package]]\nname = \"b\"\nversion = \"1\"\n[[package.dependencies]]\nname = \"a\"\n")
	// Seed 4: structurally-degenerate / empty inputs.
	f.Add("{}")
	f.Add("")
	f.Add("[[package]]\nname =")

	f.Fuzz(func(t *testing.T, lockRaw string) {
		dir := t.TempDir()
		lockPath := filepath.Join(dir, "uv.lock")
		if err := os.WriteFile(lockPath, []byte(lockRaw), 0o600); err != nil {
			t.Skip(err)
		}

		edges, err := ParseUvLock(lockPath)
		if err != nil {
			// A returned error is an acceptable outcome for malformed input;
			// what matters is no panic and no contract-violating edges.
			return
		}
		assertEdgeStructInvariants(t, edges, "fuzz-uv-lock")
	})
}

// FuzzParsePoetryLock exercises the exported poetry.lock parser
// (ParsePoetryLock). A poetry.lock (TOML) sits at the root of every scanned
// Poetry project; unlike uv.lock it omits the project package itself, so the
// parser synthesizes a virtual root over every no-incoming-edge candidate.
// Arbitrary bytes reach the TOML decoder, the [package.dependencies] map walk,
// and that synthetic-root logic. Malformed, cyclic, and wrong-typed inputs must
// all terminate without panicking, and every emitted edge must satisfy the
// structural half of the v3 per-edge contract.
func FuzzParsePoetryLock(f *testing.F) {
	// Seed 1: canonical fixture (requests -> urllib3).
	f.Add(`[[package]]
name = "requests"
version = "2.31.0"

[package.dependencies]
urllib3 = ">=1.21.1,<3"

[[package]]
name = "urllib3"
version = "2.0.7"
`)
	// Seed 2: multiple top-level deps (both no-incoming-edge -> virtual root).
	f.Add("[[package]]\nname = \"flask\"\nversion = \"3.0.0\"\n[[package]]\nname = \"click\"\nversion = \"8.1.7\"\n")
	// Seed 3: pure cycle (all-direct fallback under synthetic root).
	f.Add("[[package]]\nname = \"a\"\nversion = \"1\"\n[package.dependencies]\nb = \"*\"\n[[package]]\nname = \"b\"\nversion = \"1\"\n[package.dependencies]\na = \"*\"\n")
	// Seed 4: inline-table dependency spec + extras.
	f.Add("[[package]]\nname = \"x\"\nversion = \"1\"\n[package.dependencies]\ny = {version = \">=1\", extras = [\"a\"]}\n[[package]]\nname = \"y\"\nversion = \"2\"\n")
	// Seed 5: structurally-degenerate / empty inputs.
	f.Add("{}")
	f.Add("")
	f.Add("[[package]]\nname =")

	f.Fuzz(func(t *testing.T, lockRaw string) {
		dir := t.TempDir()
		lockPath := filepath.Join(dir, "poetry.lock")
		if err := os.WriteFile(lockPath, []byte(lockRaw), 0o600); err != nil {
			t.Skip(err)
		}

		edges, err := ParsePoetryLock(lockPath)
		if err != nil {
			return
		}
		assertEdgeStructInvariants(t, edges, "fuzz-poetry-lock")
	})
}

// FuzzParsePipfileLock exercises the exported Pipfile.lock parser
// (ParsePipfileLock). A Pipfile.lock (JSON) sits at the root of every scanned
// pipenv project; it carries no per-dep parent info, so the parser emits every
// "default"/"develop" package as a depth-1 edge off a synthetic root. Arbitrary
// bytes reach the JSON decoder and the "=="-prefix version trimming. Malformed,
// truncated, and wrong-typed inputs must all terminate without panicking, and
// every emitted edge must satisfy the structural half of the v3 per-edge
// contract.
func FuzzParsePipfileLock(f *testing.F) {
	// Seed 1: canonical fixture (one default + one develop package).
	f.Add(`{
  "_meta": {"hash": {"sha256": "test"}, "pipfile-spec": 6},
  "default": {
    "requests": {"version": "==2.31.0"}
  },
  "develop": {
    "pytest": {"version": "==7.4.0"}
  }
}`)
	// Seed 2: version without the "==" prefix + a package with no version.
	f.Add(`{"default":{"flask":{"version":"3.0.0"},"click":{}}}`)
	// Seed 3: empty object / missing sections.
	f.Add(`{}`)
	// Seed 4: wrong-typed / malformed / structural garbage.
	f.Add(`{"default":"nope"}`)
	f.Add(`{"default":{"a":`)
	f.Add(``)

	f.Fuzz(func(t *testing.T, lockRaw string) {
		dir := t.TempDir()
		lockPath := filepath.Join(dir, "Pipfile.lock")
		if err := os.WriteFile(lockPath, []byte(lockRaw), 0o600); err != nil {
			t.Skip(err)
		}

		edges, err := ParsePipfileLock(lockPath)
		if err != nil {
			return
		}
		assertEdgeStructInvariants(t, edges, "fuzz-pipfile-lock")
	})
}

// FuzzParseNuGetPackagesLock exercises the exported packages.lock.json parser
// (ParseNuGetPackagesLock) — the file `dotnet restore` writes when lock mode is
// enabled, sitting at the root of a scanned .NET project. Arbitrary bytes reach
// the JSON decoder, the per-TFM "dependencies" walk, and the Direct/Transitive
// partition. Malformed, truncated, wrong-typed, and deeply-nested inputs must
// all terminate without panicking, and every emitted edge must satisfy the
// structural half of the v3 per-edge contract.
func FuzzParseNuGetPackagesLock(f *testing.F) {
	// Seed 1: canonical fixture (1 direct + 1 transitive under net6.0).
	f.Add(`{
  "version": 1,
  "dependencies": {
    "net6.0": {
      "Newtonsoft.Json": {
        "type": "Direct",
        "requested": "[13.0.3, )",
        "resolved": "13.0.3",
        "contentHash": "test"
      },
      "Microsoft.CSharp": {
        "type": "Transitive",
        "resolved": "4.7.0",
        "contentHash": "test"
      }
    }
  }
}`)
	// Seed 2: a Direct dep declaring child "dependencies" (transitive edge).
	f.Add(`{"version":1,"dependencies":{"net8.0":{"Serilog":{"type":"Direct","resolved":"3.1.1","dependencies":{"Serilog.Sinks.Console":"5.0.0"}},"Serilog.Sinks.Console":{"type":"Transitive","resolved":"5.0.0"}}}}`)
	// Seed 3: empty object / missing dependencies.
	f.Add(`{}`)
	// Seed 4: wrong-typed / malformed / structural garbage.
	f.Add(`{"dependencies":"nope"}`)
	f.Add(`{"dependencies":{"net6.0":`)
	f.Add(``)

	f.Fuzz(func(t *testing.T, lockRaw string) {
		dir := t.TempDir()
		lockPath := filepath.Join(dir, "packages.lock.json")
		if err := os.WriteFile(lockPath, []byte(lockRaw), 0o600); err != nil {
			t.Skip(err)
		}

		edges, err := ParseNuGetPackagesLock(lockPath)
		if err != nil {
			return
		}
		assertEdgeStructInvariants(t, edges, "fuzz-nuget-packages-lock")
	})
}
